services:
  app:
    build: .
    restart: always
    container_name: 'radius_core'
    ports: 
      - '8080:8000'
    env_file:
      - ".env"
    volumes:
      - ./logs:/app/logs
    labels:
      logging.jobname: radius_core
