[project]
name = "radius-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aio-pika>=9.5.5",
    "fastapi>=0.116.1",
    "pydentic>=0.0.1.dev3",
    "redis>=6.2.0",
    "uvicorn>=0.35.0",
    "uvloop>=0.21.0",
]
