"""Конфигурация приложения."""

from .settings import (
    REDIS_URL,
    REDIS_POOL_SIZE,
    REDIS_CONCURRENCY,
    REDIS_COMMAND_TIMEOUT,
    REDIS_WARNING_THRESHOLD,
    AMQP_URL,
    AMQP_EXCHANGE,
    AMQP_SESSION_QUEUE,
    AMQP_TRAFFIC_QUEUE,
    AMQP_AUTH_LOG_QUEUE,
    AMQP_COA_QUEUE,
    RADIUS_SESSION_PREFIX,
    RADIUS_LOGIN_PREFIX,
    RADIUS_INDEX_NAME,
    PROMETHEUS_MULTIPROC_DIR,
)

__all__ = [
    "REDIS_URL",
    "REDIS_POOL_SIZE",
    "REDIS_CONCURRENCY",
    "REDIS_COMMAND_TIMEOUT",
    "REDIS_WARNING_THRESHOLD",
    "AMQP_URL",
    "AMQP_EXCHANGE",
    "AMQP_SESSION_QUEUE",
    "AMQP_TRAFFIC_QUEUE",
    "AMQP_AUTH_LOG_QUEUE",
    "AMQP_COA_QUEUE",
    "RADIUS_SESSION_PREFIX",
    "RADIUS_LOGIN_PREFIX",
    "RADIUS_INDEX_NAME",
    "PROMETHEUS_MULTIPROC_DIR",
]
